// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTNyzL-fFUjfViZVDSxda13VlT53tnII0',
    appId: '1:505765642038:web:da41537bdfced786473d97',
    messagingSenderId: '505765642038',
    projectId: 'elite-academy-flutter',
    authDomain: 'elite-academy-flutter.firebaseapp.com',
    storageBucket: 'elite-academy-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-euWRMXoWFVb0ZRnTGbzLbd0pHgglwIg',
    appId: '1:505765642038:android:f2ae7b880d0a91a0473d97',
    messagingSenderId: '505765642038',
    projectId: 'elite-academy-flutter',
    storageBucket: 'elite-academy-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNLPrOfsW2WUITI3c1d-MmEFYioL_kKnw',
    appId: '1:505765642038:ios:b5c3a7556568a194473d97',
    messagingSenderId: '505765642038',
    projectId: 'elite-academy-flutter',
    storageBucket: 'elite-academy-flutter.appspot.com',
    iosBundleId: 'edu.aeronex.eliteAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNLPrOfsW2WUITI3c1d-MmEFYioL_kKnw',
    appId: '1:505765642038:ios:0b7b0c52f93e0a10473d97',
    messagingSenderId: '505765642038',
    projectId: 'elite-academy-flutter',
    storageBucket: 'elite-academy-flutter.appspot.com',
    iosBundleId: 'edu.aeronex.eliteAcademy.RunnerTests',
  );
}
